### ISSUE TITLE
BezelImageView flag error

### ISSUE THREAD

**Issue by illomi7** [amatkivskiy/MaterialDrawer-Xamarin#10]
Hi,
I see that there is a pull request that resolve bezelimageview flag error.
Is possible to merge the pull request and publish a new version on nuget, it could help me a lot.

Thank you.

**Comment by felipecds** [comment]
He is not maintaining this repo anymore, go to my fork, download and build it. After, add manually the .dll references to your project and remove any nuget package.

**Comment by amatkivskiy** [comment]
@illomi7  @felipecds Yes, this repository is no longer maintained. Please use forks instead.
