### ISSUE TITLE
Why do you run the pop-up menu after the first installation?

### ISSUE THREAD

**Issue by xlievo** [amatkivskiy/MaterialDrawer-Xamarin#3]
Only after the first installation.

```
                         Thank you!
```

**Comment by amatkivskiy** [comment]
@xlievo What do you mean by pop-up menu? can you provide any screenshot?

**Comment by xlievo** [comment]
When.apk is installed the first run
Drawer will automatically slide out once
For the first run.

Please excuse my language skills. Thank you!

**Comment by xlievo** [comment]
What did I do wrong? 
//=======================================//
headerResult = new AccountHeaderBuilder()
            .WithActivity(this)
            .WithHeaderBackground(Resource.Drawable.header)
            .AddProfiles(profile)
            .WithOnAccountHeaderListener(this)
            .WithSavedInstance(bundle)
            .WithThreeSmallProfileImages(false)
            .WithCompactStyle(true)
            .WithSelectionListEnabledForSingleProfile(false)
            .WithTranslucentStatusBar(false)
            .WithHeightDp(75)
            .Build();
//=======================================//
result = new DrawerBuilder()
            .WithActivity(this)
            .WithToolbar(toolbar)
            .WithSliderBackgroundColorRes(Resource.Color.GhostWhite)
            .WithStatusBarColorRes(Resource.Color.GhostWhite)
            .WithAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
            .AddDrawerItems(
                item1,
                item2,
                new SectionDrawerItem().WithName("Control").WithTextColorRes(Resource.Color.DimGray),
                item3,
                new DividerDrawerItem()
            ) // add the items we want to use With our Drawer
            .WithOnDrawerItemClickListener(this)
            .WithSavedInstance(bundle)
            .WithShowDrawerOnFirstLaunch(true)
            .Build();

```
        if (bundle == null)
        {
            result.SetSelection(-1);
        }
```

![aaa](https://cloud.githubusercontent.com/assets/5188470/9327368/da20dbd4-45d2-11e5-9970-34d055707a30.png)

```
                                                              Thank you!
```

**Comment by xlievo** [comment]
I seem to have found the reason.

WithShowDrawerOnFirstLaunch(true)

This will trigger an automatic pop-up drawer!
Problem solving Thank you!

**Comment by amatkivskiy** [comment]
@xlievo ok)
