### ISSUE TITLE
9 errors: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Anapher** [amatkivskiy/MaterialDrawer-Xamarin#4]
Hello,
i'm getting 9 errors when I try to run my app. I just added the nuget package.

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/google_material_typeface_library/GoogleMaterial$Icon;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/google_material_typeface_library/GoogleMaterial;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/BuildConfig;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$1;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$IconicsBuilder;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$IconicsBuilderString;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$IconicsBuilderView;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$RemoveInfo;

COMPILETODALVIK : Uncaught translation error : java.lang.IllegalArgumentException: already added: Lcom/mikepenz/iconics/Iconics$StyleContainer;

(that's from the log)

Would be nice if you can fix this :)

**Comment by amatkivskiy** [comment]
@Alkalinee I will try to fix this bug in few days.

**Comment by Anapher** [comment]
That would be awesome :)

**Comment by amatkivskiy** [comment]
@Alkalinee Please try updated version (4.5.8).

**Comment by Anapher** [comment]
AWESOME, thank you very much, everything works fine now :)
