### ISSUE TITLE
primarydraweritem WithDescription return java.lang.object

### ISSUE THREAD

**Issue by lobster2012-user** [amatkivskiy/MaterialDrawer-Xamarin#6]
Спасибо за порт.
К сожалению не получается использовать флуент синтаксис из-за типа возвращаемого параметра.
Я так понимаю проблема настройках xamarin bindings
(у меня скачана нугет версия)
Спасибо.

**Comment by amatkivskiy** [comment]
Sorry but this is known issue. This is due to the different generic systems of Java and C#. There is nothing you can do with this😞

**Comment by lobster2012-user** [comment]
Ок.
I wrote few extensions methods for some methods with same names

**Comment by amatkivskiy** [comment]
@lobster2012-user cool, I think this is the best workaround for this.

**Comment by lobster2012-user** [comment]
I found generator.exe in C:\Program Files (x86)\MSBuild\Xamarin\Android
It contains xamarin android generator code (internal)
Inside a lot of things internal.
You can use the inject .or
You can copy most of the code and use your generator . Too much work to override the 3 methods , I hope Xamarin add the ability to use own generator with little extra code

May be i can add extra task to override generates files, i do not work with msbuild

**Comment by lobster2012-user** [comment]
For other jar lib i did hide some methods with metadata.xml and add partial class code with few methods in folder additions.

**Comment by amatkivskiy** [comment]
@lobster2012-user yes, this is exactly what I did. Sometimes you need to rename or remove deprecated methods. Besides metada.xml I forked https://github.com/amatkivskiy/jar2xml and extended it with ability to parse sources of java libraries to have proper parameters names in methods.
